changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - feature
        - feat
    - title: Bug Fixes
      labels:
        - bugfix
        - fix
    - title: Other Changes
      labels:
        - "*"
