site_name: Rarible Protocol
site_description: Rarible Protocol documentation

nav:
  - 'Home': 'index.md'
  - 'Getting Started':
      - 'Quick Start': 'getting-started/quick-start.md'
      - 'Community and resources': 'getting-started/community.md'
      - 'Reasons for using protocol': 'getting-started/reasons.md'
      - 'Glossary': 'getting-started/glossary.md'
  - 'Rarible Protocol':
      - 'Overview': 'overview/union.md'
      - 'Ethereum':
          - 'Ethereum Overview': 'ethereum/ethereum-overview.md'
          - 'Contract Addresses': 'ethereum/contract-addresses.md'
          - 'Smart Contracts':
              - 'Smart Contracts Overview': 'ethereum/smart-contracts/smart-contracts.md'
              - 'ExchangeV2':
                  - 'ExchangeV2 Overview': 'ethereum/smart-contracts/exchangev2-overview.md'
                  - 'ExchangeV2 Matching Orders': 'ethereum/smart-contracts/exchangev2-matching-orders.md'
                  - 'ExchangeV2 Sell and Bid': 'ethereum/smart-contracts/exchangev2-sell-bid.md'
                  - 'ExchangeV2 Update and Cancel': 'ethereum/smart-contracts/exchangev2-update-cancel.md'
              - 'Tokens': 'ethereum/smart-contracts/tokens.md'
              - 'Fees': 'ethereum/smart-contracts/fees.md'
              - 'Royalties': 'ethereum/smart-contracts/royalties.md'
          - 'API and Indexer':
              - 'API and Indexer Overview': 'ethereum/api/ethereum-api-indexer.md'
              - 'Search Items': 'ethereum/api/search-items.md'
              - 'Search Orders': 'ethereum/api/search-orders.md'
              - 'Create Lazy Minting': 'ethereum/api/create-lazy-minting.md'
              - 'Create Orders': 'ethereum/api/create-orders.md'
          - 'Ethereum SDK': 'ethereum/sdk/ethereum-sdk.md'
          - 'Metadata':
              - 'Ethereum Metadata': 'ethereum/metadata/ethereum-metadata.md'
              - 'Example of uploading and using Metadata with IPFS': 'ethereum/metadata/ipfs-example.md'
      - 'Tezos':
          - 'Tezos Overview': 'tezos/tezos-overview.md'
          - 'Contract Addresses': 'tezos/tezos-contract-addresses.md'
      - 'Flow':
          - 'Flow Overview': 'flow/flow-overview.md'
          - 'Flow SDK': 'flow/flow-sdk.md'
          - 'Flow Smart Contracts': 'flow/flow-smart-contracts.md'
          - 'Flow API and Indexer': 'flow/flow-api-indexer.md'
  - 'API': 'api-reference.md'
  - 'SDK':
         - 'Overview': 'union-sdk.md'
         - 'API Usage with SDK': 'union-sdk/api.md'
         - 'Transfer, Mint, Burn': 'union-sdk/nft.md'
         - 'Sell, Bid, Fill': 'union-sdk/order.md'
  - 'Use Cases':
      - 'Picnic': 'use-cases/picnic.md'
      - 'cocoNFT': 'use-cases/coconft.md'
      - 'MintGate': 'use-cases/mintgate.md'
      - 'EZCode SDK plugin': 'use-cases/bubblesdk.md'
      - 'Moralis Lazy Mint & Sell plugin': 'use-cases/moralisplugin.md'
      - 'Setting Up Royalties on an External Collection': 'use-cases/royalties-on-a-external-collection.md'
  - 'FAQ': 'faq.md'

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

plugins:
  - search
repo_url: https://github.com/rarible/protocol
repo_name: rarible/protocol

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zqsZsEWBbN
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raribledao
    - icon: fontawesome/brands/github
      link: https://github.com/rarible
  analytics:
    provider: google
    property: G-20ZJ98JPQ3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our <a href="https://github.com/rarible/protocol/issues/new/?title=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeat visits and preferences
      and measure the effectiveness of our documentation and whether users
      find what they're searching for. Thank you for helping us improve the documentation.

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
  - meta
